# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/brown_photostudio_01_concated'

# data
image_path: 'data/brown_photostudio_01_concated.jpg'
latents_path: 'latents_forward'

# diffusion
sd_version: '2.1'
guidance_scale: 7.5
n_timesteps: 50
prompt: a photo of watercolor painting indoor room
negative_prompt: ugly, blurry, black, low res, unrealistic

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
